source: ./assets
destination: ./styleguide
documentation_assets: ./styleguide-theme

title: 'Swiss Styleguide'

dependencies:
  - ./build/img
  - ./build/js
  - ./build/fonts
  - ./build/css
  - ./styleguide-img

# To have a custom index page build with your README.md
index: README

# List all css to include for the styleguide render examples
css_include:
  - 'css/vendors.css'
  - 'css/admin.css'
  - 'css/print.css'

# List all js to include for the styleguide render examples
js_include:
  - 'js/vendors.min.js'
  - 'js/main.min.js'

# String who is used to split the category name and create category wrapper
name_scope: ' - '

# Order of Category Wrapper
cat_order:
  - Design Principles
  - Base Layout
  - Navigation modules
  - Content Modules

static_page:
  - Homepage with Global navigation | homepage-global-nav.html
  - Homepage without Global navigation | home-without-nav.html
  - Subpage | subpage.html
  - Overview page without navigation | preview-without-nav.html
  - Overview page | preview.html
  - Publications page | publications.html
  - Details page | detail.html
  - Forms page | forms.html
  - Search result page | results.html
